project:
  type: website
  output-dir: docs

website:
  title: Elisa Baldazzi
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
  page-footer: "&#169; Elisa Baldazzi, 2025"
      

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: false
    page-layout: full

editor: visual

