project:
  type: website
  output-dir: docs

website:
  title: Elisa Baldazzi
  navbar:
    background: secondary
    search: true
    left:
      - text: Home
        file: index.qmd
      - text: Research
        file: research.qmd
      - text: Curriculum Vitae
        file: cv.qmd
  page-footer: "&#169; Elisa Baldazzi, 2025"
      

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: false
    page-layout: full

editor: visual