## **Working Papers**

-   **Seeing Sterotypes** \[[arxiv](https://arxiv.org/abs/2503.02146)\]\
    [Baldazzi, E]{.underline}., Biroli, P., Della Giusta, M., Dubois, F.\
    *arXiv preprint arXiv:2503.02146, 2025*

## **Work in Progress**

- *Cognitive and Non Cognitive Outcomes of the Scout Method*
- *Do LVLMs See Stereotypes as We Do? A Social Science Framework for Evaluating LVLMs’ Recognition and Explanation of Stereotypes in Images* with Marco Madeddu, Chiara Ferrando, Horacio Jarquín Vásquez, Marina Della Giusta, Viviana Patti.


## **Presentations**

- **Seeing Sterotypes**\
  *Contributed talk at the [Workshop on the Economics of Education](https://feb.kuleuven.be/drc/LEER/bridge-project/workshop-on-the-economics-of-education){style="text-decoration: none"}, Leuven, Belgium\
  *November 2025

- **Seeing Sterotypes**\
  *Contributed talk at the [ESPE 2025](https://www.espe2025naples.com/){style="text-decoration: none"}, Naples, Italy\
  *June 2025

- **Seeing Sterotypes**\
  *Contributed talk at the [4th Workshop On Gender and Economics](https://inomics.com/conference/call-for-papers-4th-workshop-on-gender-and-economics-1547797#:~:text=The%20fourth%20edition%20of%20the,on%2022%2D23%20May%202025.){style="text-decoration: none"}, Luxembourg, Luxembourg\
  *May 2025

- **Seeing Sterotypes**\
  *Contributed talk at the [Bolzano Applied Microeconomics Workshop](https://www.unibz.it/en/events/bolzano-applied-microeconomics-workshop-2025){style="text-decoration: none"}, Bolzano, Italy\
  *March 2025